version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - MIX_ENV=dev
    command: bash -c "mix ecto.create && mix ecto.migrate && mix run --no-halt"
  db:
    image: postgres:15.7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library_app_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
